### ISSUE TITLE
Torrent quality

### ISSUE THREAD

**Issue by fabienfoerster** [teambrookie/showrss#1]
@etiennestrobbe je me demandais ce que tu pensais pour la qualité des épisodes ...
Parce que moi de base je vais dire que je bloque sur du 720p.
Mais il y a des épisodes qui sortent en 1080p et même 2160p  Et ça t'intéresse ou pas ?
Parce que moi avant de DL un ep en 1080p je peux m'accrocher quoi .

Voilà bisous

**Comment by etiennestrobbe** [comment]
Je voudrais pas casser tes rêves mais le 2160p c'est du 4K (3840x2160). Je
sais j'ai pas répondu à ta question.

Le 17 déc. 2016 4:46 PM, "Fabien Foerster" <notifications@github.com> a
écrit :

**Comment by fabienfoerster** [comment]
Ok donc sympa mais pas essentiel !
